headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\WRO2026\\simulator\\pdf-w3f\\viz_3d"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/textures/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/data/*"

[headers.values]
Cache-Control = "public, max-age=3600"

[[redirects]]
from = "/"
to = "/demo.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/dashboard"
to = "/dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/demo.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]